import "./globals.css";
import { Inter } from "next/font/google";
import { MantineProvider } from "@mantine/core";
import ThemeProvider from "@/components/theme_provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Codelearn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
